<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyTitle>F31 Mastermind AWS Professor Debugger</AssemblyTitle>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
        <FileVersion>1.0.0.0</FileVersion>
        <Company>YNAP</Company>
        <Authors>Matteo Tinta (F31)</Authors>
        <Product>F31 Mastermind AWS Professor Debugger</Product>
        <Description>CLI to traverse AWS resource dependencies.</Description>
        <Copyright>Copyright (c) Matteo Tinta (F31)</Copyright>
    </PropertyGroup>
    
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Core\Core.csproj" />
      <ProjectReference Include="..\Momo.Commands\Momo.Commands.Rest\Momo.Commands.Rest.csproj" />
      <ProjectReference Include="..\Momo.Commands\Momo.Commands.S3\Momo.Commands.S3.csproj" />
      <ProjectReference Include="..\Momo.Expectations\Momo.Expectations.Mongo\Momo.Expectations.Mongo.csproj" />
      <ProjectReference Include="..\Momo.Expectations\Momo.Expectations.Parallel\Momo.Expectations.Parallel.csproj" />
      <ProjectReference Include="..\Momo.Expectations\Momo.Expectations.S3\Momo.Expectations.S3.csproj" />
      <ProjectReference Include="..\Momo.Expectations\Momo.Expectations.SNS\Momo.Expectations.SNS.csproj" />
      <ProjectReference Include="..\Momo\Momo.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.IdentityManagement" Version="4.0.3.2" />
        <PackageReference Include="AWSSDK.Lambda" Version="4.0.2.8" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.6.12" />
        <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.1.1" />
        <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="4.0.3.1" />
        <PackageReference Include="AWSSDK.SQS" Version="4.0.1.2" />
        <PackageReference Include="AWSSDK.SSO" Version="4.0.1.1" />
        <PackageReference Include="AWSSDK.SSOOIDC" Version="4.0.1.1" />
      <PackageReference Include="CommandLineParser" Version="2.9.1" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-rc.1.25451.107" />
      <PackageReference Include="NJsonSchema" Version="11.5.0" />
    </ItemGroup>

</Project>
