using System.Text.RegularExpressions;
using CommandLine;
using Core.Cache.Providers;

namespace Cli
{
    [Verb("momo", HelpText = "Feeds Momo with a new file for request matching.")]
    internal class MomoOptions
    {
        [Value(0, Required = true, HelpText = "Path to the input file.")]
        public string InputFile { get; set; }

        [Option('a', "auto", Required = false, Default = false, HelpText = "Auto generation mode, will overwrite your existing file with autogenerated standard metadata.")]
        public bool Auto { get; set; }

        // [Option("ignore-cache", Default = false, HelpText = "Ignore stored cache.")]
        // public bool IgnoreCache { get; set; }
    }
    
    [Verb("graph", HelpText = "Analyze AWS ARN and explore graph resources.")]
    internal class GraphOptions
    {
        [Value(0, Required = true, HelpText = "AWS ARN to process.")]
        public string AwsArn { get; set; }

        [Option("ignore-cache", Default = false, HelpText = "Ignore stored cache. Actual present cache file will be overidden.")]
        public bool IgnoreCache { get; set; }

        [Option("output-as", Default = GraphPrinterType.Cli, HelpText = "Cli, Json, Graph or Momo (case sensitive)")]
        public GraphPrinterType OutputAs { get; set; }
        
        [Option("output-to", HelpText = "Path to save the output (required and used only if --output-as=Momo)")]
        public string OutputTo { get; set; }

        ////TODO
        [Option("cache-type", Default = CacheType.JsonFile, HelpText = "Only JsonFile is available for now (case sensitive)")]
        public CacheType CacheType { get; set; }

        [Option("max-level", Required = false, HelpText = "Set the max level to stop")]
        public int? MaxLevel { get; set; }
        
        public bool Validate(out string error)
        {
            if (!IsValidArn(AwsArn))
            {
                error = "Provided Arn is not valid";
                return false;
            }
            
            if (OutputAs == GraphPrinterType.Momo)
            {
                if (string.IsNullOrWhiteSpace(OutputTo))
                {
                    error = "When --output-as=Momo is used, --output-to must also be specified.";
                    return false;
                }

                if (!OutputTo.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
                {
                    error = "When --output-as=Momo is used, --output-to must end with .json.";
                    return false;
                }

                // controlla anche se la directory esiste
                var dir = Path.GetDirectoryName(OutputTo);
                if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
                {
                    error = $"Directory does not exist: {dir}";
                    return false;
                }
            }

            error = null;
            return true;
        }
        
        public bool IsValidArn(string arn)
        {
            var pattern = @"^arn:(aws|aws-cn|aws-us-gov):[a-z0-9-]+:[a-z0-9-]*:\d{0,12}:[^:\s]+(:[^:\s]+)*$";
            return Regex.IsMatch(arn, pattern);
        }
    }

    internal class CliHandler
    {
        public ParsedCliResult? ParseArguments(string[] args)
        {
            ParsedCliResult? result = null;
            
            Parser.Default.ParseArguments<MomoOptions, GraphOptions>(args)
                .WithParsed<MomoOptions>(options =>
                {
                    result = new ParsedCliResult(CommandType.Momo, options);
                })
                .WithParsed<GraphOptions>(options =>
                {
                    if (!options.Validate(out var error))
                    {
                        Console.Error.WriteLine(error);
                        Environment.Exit(1);
                    }
                    
                    result = new ParsedCliResult(CommandType.Graph, options);
                })
                .WithNotParsed(errors =>
                {
                    Environment.Exit(1);
                });

            return result;
        }

        
    }
    
}

public enum CommandType
{
    Graph,
    Momo
}

internal record ParsedCliResult(
    CommandType Command,
    object Options
);
