using Cli.FileLoader;
using Momo;
using Momo.Models;

namespace Cli;

internal class MomoCliHandler : IAsyncDisposable
{
    private readonly IMomoClient _client;

    public MomoCliHandler(
        MomoClientFactoryOptions options,
        MomoOptions cliMomoOptions)
    {
        //clients
        _client = MomoClientFactory.FeedMomo(options);
        _client.OnAllExpectationsMatch = async void (updatedFile) =>
        {
            await SaveChanges(cliMomoOptions, updatedFile);
        };
    }
    
    public async Task ExecuteMomo()
    {
        await _client.MatchExpectations(CancellationToken.None);
    }

    private async Task SaveChanges(MomoOptions momoOptions, MomoExpectationFile file)
    {
        if (_client is AutoMomoClient autoMomoClient)
        {
            //Save json?
            await MomoFileLoader.SaveAsync(autoMomoClient.ExpectationFile!, momoOptions.InputFile);
            Console.WriteLine($"[SUCCESS]: Expectation generated sucessfully and saved to {momoOptions.InputFile}");
            Console.WriteLine($"[WARNING]: Autogenerated files are considered templates! You are supposed to modify them to create proper tests");
            Console.WriteLine($"[WARNING]: In case of dates in ISO format which have time in it, remember to change date to date-time (external library known bug)");
        }
        else
        {
            await MomoFileLoader.SaveAsync(file, momoOptions.InputFile);
            Console.WriteLine($"[SUCCESS]: Expectation file updated...");
        }
    }

    public async ValueTask DisposeAsync()
    {
        await _client.DisposeAsync();
    }
}