using Cli.FileLoader;
using Momo;
using Momo.Models;

namespace Cli;

internal class MomoCliHandler : IAsyncDisposable
{
    private readonly IMomoClient _client;
    private readonly CancellationTokenSource _cancellationTokenSource;

    public MomoCliHandler(
        MomoClientFactoryOptions options,
        MomoOptions cliMomoOptions)
    {
        //cancellation management
        _cancellationTokenSource = new CancellationTokenSource();
        
        //client and callbacks
        bool commandsRan = false;
        _client = MomoClientFactory.FeedMomo(options);
        
        _client.OnExpectationPrepared = async void (_,_) =>
        {
            if (commandsRan) 
                return;
            
            commandsRan = true;
            
            await _client.ExecuteCommands(_cancellationTokenSource.Token);
        };
        
        _client.OnAllExpectationsMatch = async void (updatedFile) =>
        {
            await SaveChanges(cliMomoOptions, updatedFile);
        };
    }
    
    public async Task ExecuteMomo()
    {
        try
        {
            await _client.MatchExpectations(_cancellationTokenSource.Token);
        }
        catch (Exception)
        {
            await DisposeAsync();
            throw;
        }
    }

    private async Task SaveChanges(MomoOptions momoOptions, MomoExpectationFile file)
    {
        await MomoFileLoader.SaveAsync(file, momoOptions.InputFile);

        if (_client is AutoMomoClient)
        {
            Console.WriteLine($"[SUCCESS]: Expectation generated sucessfully and saved to {momoOptions.InputFile}");
            Console.WriteLine($"[WARNING]: Autogenerated files are considered templates! You are supposed to modify them to create proper tests");
            Console.WriteLine($"[WARNING]: In case of dates in ISO format which have time in it, remember to change date to date-time (external library known bug)");
        }
    }

    public async ValueTask DisposeAsync()
    {
        //Stop all inner tasks immediately...
        await _cancellationTokenSource.CancelAsync();
        
        //Dispose dangling resources...
        await _client.DisposeAsync();
    }
}