using Momo.Exceptions;
using Momo.Expectations;
using Momo.Helpers;
using Momo.Models;
using Momo.Steps;
using Momo.Steps.Decorations;
using Newtonsoft.Json;

namespace Momo;

public class AutoMomoClient(MomoClientFactoryOptions Options) : IMomoClient
{
    public MomoExpectationFile? ExpectationFile { get; private set; }

    public Action<IMomoExpectation>? OnExpectationMatch { get; set; }
    
    public Action<MomoExpectationFile>? OnAllExpectationsMatch { get; set; }
    
    private readonly List<IStepHandler> _ranExpectations = [];

    public async Task MatchExpectations(CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        
        List<IMomoExpectation> autogeneratedExpectations = [];
        
        var timeout = TimeSpan.FromSeconds(Options.ExpectationFile.Timeout);
        foreach (var expectation in Options.ExpectationFile.Expectations)
        {
            try
            {
                var expectations = await TimeoutHelpers.TimeoutAsync(timeout, c => CheckAsync(expectation, c), cancellationToken);
                autogeneratedExpectations.AddRange(expectations);
            }
            catch (OperationCanceledException e)
            {
                throw new AssertException(
                        $"Unable to check expectation in given timeout ({Options.ExpectationFile.Timeout} seconds)",
                        new AssertException($"Current Expectation was:\n{JsonConvert.SerializeObject(expectation, Formatting.Indented)}", e))
                    .BreakWhenRaised();
            }
        }
        
        ExpectationFile = Options.ExpectationFile with
        {
            Expectations = autogeneratedExpectations
        };
        
        OnAllExpectationsMatch?.Invoke(ExpectationFile);
    }
    
    private async Task DisposeStep(IStepHandler step)
    {
        await step.DisposeAsync();
        _ranExpectations.Remove(step);
    }
    
    private async Task<List<IMomoExpectation>> CheckAsync(IMomoExpectation expectation, CancellationToken cancellationToken)
    {
        List<IMomoExpectation> autogeneratedExpectations = [];
        
        var step = expectation.GetStepHandler(Options);
        var stepButDecorated = new StepHandlerLoggingDecorated(step, Options);

        var registration = cancellationToken.Register(async () => await DisposeStep(stepButDecorated));

        try
        {
            await stepButDecorated.PrepareAsync(expectation, cancellationToken);
            
            _ranExpectations.Add(stepButDecorated);
                
            var result = await RetryHelper.RetryAsync(
                async () => await stepButDecorated.GenerateExpectationAsync(expectation, cancellationToken),
                cancellationToken);
                
            autogeneratedExpectations.Add(result);
                
            OnExpectationMatch?.Invoke(expectation);
        }
        finally
        {
            await registration.DisposeAsync();
            
            await DisposeStep(stepButDecorated);
        }

        return autogeneratedExpectations;
    }

    public async ValueTask DisposeAsync()
    {
        await Task.WhenAll(_ranExpectations.Select(e => e.DisposeAsync().AsTask()));
    }
}