using Momo.Exceptions;
using Momo.Expectations;
using Momo.Helpers;
using Momo.Models;
using Momo.Steps;
using Momo.Steps.Decorations;
using Newtonsoft.Json;

namespace Momo;

public interface IMomoClient: IAsyncDisposable
{
    public Action<IMomoExpectation>? OnExpectationMatch { get; set; }
    
    public Action<MomoExpectationFile>? OnAllExpectationsMatch { get; set; }
    
    public Task MatchExpectations(CancellationToken cancellationToken);
}

public class MomoClient: IMomoClient
{
    private readonly MomoClientFactoryOptions _options;

    private MomoClient(MomoClientFactoryOptions options)
    {
        _options = options;
    }

    public Action<IMomoExpectation>? OnExpectationMatch { get; set; }
    
    public Action<MomoExpectationFile>? OnAllExpectationsMatch { get; set; }
    
    private readonly List<IStepHandler> _ranExpectations = [];

    public async Task MatchExpectations(CancellationToken cancellationToken)
    {
        foreach (var expectation in _options.ExpectationFile.Expectations)
        {
            var step = expectation.GetStepHandler(_options);
            var stepButDecorated = new StepHandlerLoggingDecorated(step);
            _ranExpectations.Add(stepButDecorated);
            
            try
            {
                await stepButDecorated.PrepareAsync(expectation, cancellationToken);

                var timeout = TimeSpan.FromSeconds(_options.ExpectationFile.Timeout);
                
                var result = await RetryHelper.RetryAsync(
                    async () => await stepButDecorated.CheckAsync(expectation, _options.ExpectationFile.Timeout, cancellationToken),
                        timeout, cancellationToken);

                if (!result)
                {
                    throw new AssertException($"Step {JsonConvert.SerializeObject(expectation)} failed");
                }
                
                OnExpectationMatch?.Invoke(expectation);
            }
            finally
            {
                await stepButDecorated.DisposeAsync();
            }
        }
        
        OnAllExpectationsMatch?.Invoke(_options.ExpectationFile);
    }

    internal static MomoClient ValidateAndCreate(MomoClientFactoryOptions options)
    {
        try
        {
            options.ExpectationFile.ValidateAllExpectations();
        }
        catch (MomoFileValidationException e)
        {
            throw new MomoClientValidationException("Current Expectation File Is Invalid", e);
        }
        
        return new(options);
    }

    public async ValueTask DisposeAsync()
    {
        await Task.WhenAll(_ranExpectations.Select(e => e.DisposeAsync().AsTask()));
    }
}

public class AutoMomoClient(MomoClientFactoryOptions Options) : IMomoClient
{
    public MomoExpectationFile? ExpectationFile { get; private set; }

    public Action<IMomoExpectation>? OnExpectationMatch { get; set; }
    
    public Action<MomoExpectationFile>? OnAllExpectationsMatch { get; set; }
    
    private readonly List<IStepHandler> _ranExpectations = [];

    public async Task MatchExpectations(CancellationToken cancellationToken)
    {
        var expectationFile = Options.ExpectationFile;
        
        List<IMomoExpectation> autogeneratedExpectations = [];
        
        foreach (var expectation in expectationFile.Expectations)
        {
            var step = expectation.GetStepHandler(Options);
            var stepButDecorated = new StepHandlerLoggingDecorated(step);
            
            _ranExpectations.Add(stepButDecorated);
            
            try
            {
                await stepButDecorated.PrepareAsync(expectation, cancellationToken);
                
                //TODO: Add timeout callback!
                var timeout = TimeSpan.FromSeconds(expectationFile.Timeout);
                var result = await RetryHelper.RetryAsync(
                    async () => await stepButDecorated.GenerateExpectationAsync(expectation, cancellationToken),
                    timeout, cancellationToken);
                
                autogeneratedExpectations.Add(result);
                
                OnExpectationMatch?.Invoke(expectation);
            }
            finally
            {
                await stepButDecorated.DisposeAsync();
            }
        }

        ExpectationFile = Options.ExpectationFile with
        {
            Expectations = autogeneratedExpectations
        };
        
        OnAllExpectationsMatch?.Invoke(ExpectationFile);
    }

    public async ValueTask DisposeAsync()
    {
        await Task.WhenAll(_ranExpectations.Select(e => e.DisposeAsync().AsTask()));
    }
}