using Momo.Exceptions;
using Momo.Expectations;
using Momo.Helpers;
using Momo.Models;
using Momo.Steps.Decorations;
using Newtonsoft.Json;

namespace Momo;

public interface IMomoClient
{
    public Task MatchExpectations(CancellationToken cancellationToken);
}

public class MomoClient: IMomoClient
{
    private readonly MomoClientFactoryOptions _options;

    private MomoClient(
        MomoClientFactoryOptions options)
    {
        _options = options;
    }

    public async Task MatchExpectations(CancellationToken cancellationToken)
    {
        foreach (var expectation in _options.ExpectationFile.Expectations)
        {
            var step = expectation.GetStepHandler(_options);
            var stepButDecorated = new StepHandlerLoggingDecorated(step);
            
            try
            {
                await stepButDecorated.PrepareAsync(expectation, cancellationToken);

                var timeout = TimeSpan.FromSeconds(_options.ExpectationFile.Timeout);
                
                var result = await RetryHelper.RetryAsync(
                    async () => await stepButDecorated.CheckAsync(expectation, _options.ExpectationFile.Timeout, cancellationToken),
                        timeout, cancellationToken);

                if (!result)
                {
                    throw new AssertException($"Step {JsonConvert.SerializeObject(expectation)} failed");
                }
            }
            finally
            {
                await stepButDecorated.DisposeAsync();
            }
        }
    }

    internal static MomoClient ValidateAndCreate(MomoClientFactoryOptions options) => new(options);
}

public class AutoMomoClient(MomoClientFactoryOptions Options) : IMomoClient
{
    public MomoExpectationFile? ExpectationFile { get; private set; }

    public async Task MatchExpectations(CancellationToken cancellationToken)
    {
        var expectationFile = Options.ExpectationFile;
        
        List<IMomoExpectation> autogeneratedExpectations = [];
        
        foreach (var expectation in expectationFile.Expectations)
        {
            var step = expectation.GetStepHandler(Options);
            var stepButDecorated = new StepHandlerLoggingDecorated(step);
            
            try
            {
                await stepButDecorated.PrepareAsync(expectation, cancellationToken);
                
                //TODO: Add timeout callback!
                var timeout = TimeSpan.FromSeconds(expectationFile.Timeout);
                var result = await RetryHelper.RetryAsync(
                    async () => await stepButDecorated.GenerateExpectationAsync(expectation, cancellationToken),
                    timeout, cancellationToken);
                
                autogeneratedExpectations.Add(result);
            }
            finally
            {
                await stepButDecorated.DisposeAsync();
            }
        }

        ExpectationFile = Options.ExpectationFile with
        {
            Expectations = autogeneratedExpectations
        };
    }
}